apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-server-pv
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/palworld-data"
