apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/sonarr/tv"
  storageClassName: "fast-nvme-sonarr-tv"