apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/overseerr/"
  storageClassName: "fast-nvme-overseerr"