apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgres
  labels:
    app: postgresql
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/postgresql"