apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-redis
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/gitea/redis"