apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Name }}-server
  name: {{ .Release.Name }}-server-datadir
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
