apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  rconPassword: {{ .Values.secret.rconPassword | quote | default (required "A rconPassword is required" .Values.secret.rconPassword) }}
