apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-server
  name: {{ .Release.Name }}-server
spec:
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-server
  type: {{ .Values.service.type }}
