apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-nvme-nextcloud-config
  hostPath:
    path: "/mnt/nextcloud/config"  # Adjust the path as necessary
