apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-psql
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/nextcloud/psql"