image:
  tag: v1.108.0 # v1.106.1 by default

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc

server:
  service:
    main:
      type: LoadBalancer

machine-learning:
  persistence:
    cache:
      existingClaim: immich-machine-learning-cache

postgresql:
  enabled: true

redis:
  enabled: true