image:
  tag: v1.108.0 # v1.106.1 by default

immich:
  persistence:
    library:
      existingClaim: immich-library-pvc

server:
  # Uncomment this if you don't have an ingress in your Kubernetes cluster 
  # and need an external IP for the immich service
  # service:
  #   main:
  #     type: LoadBalancer
  ingress:
    main:
      enabled: false # prefer using an external Ingress definition

machine-learning:
  persistence:
    cache:
      existingClaim: immich-machine-learning-cache

postgresql:
  enabled: true

redis:
  enabled: true