apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-psql
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/immich/psql"