apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-redis-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/immich/redis-data"