apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-machine-learning-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/immich/ml-cache"
  storageClassName: fast-nvme