apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: immich-redis