apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-psql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: paperless-psql