apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/paperless/media"