apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-io-https
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: demo.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 443
  tls:
  - hosts:
    - demo.io
    secretName: demo-io-tls