apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-gitea
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.2
    path: "/mnt/user/gitea"
  mountOptions:
    - nfsvers=4.2