apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-torrent
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.7
    path: "/torrent"
  mountOptions:
    - nfsvers=4.1 # QNAP limitation