apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-nextcloud