apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/jellyfin/config"
