apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-cache
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/jellyfin/cache"
