apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-pv
  labels:
    app: redis-master
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/redis/master"